# Adapted from geopandas and earthpy setup
# https://github.com/geopandas/geopandas/blob/master/appveyor.yml
# https://github.com/earthlab/earthpy/blob/master/appveyor.yml

matrix:
  fast_finish: true     # immediately finish build once one of the jobs fails.

environment:
  matrix:
    - PYTHON_VERSION: "3.6"
      MINICONDA: C:\Miniconda36-x64

build: false

init:
  - "ECHO %PYTHON_VERSION% %MINICONDA%"

install:
  # cancel older builds for the same PR
  - ps: if ($env:APPVEYOR_PULL_REQUEST_NUMBER -and $env:APPVEYOR_BUILD_NUMBER -ne ((Invoke-RestMethod `
        https://ci.appveyor.com/api/projects/$env:APPVEYOR_ACCOUNT_NAME/$env:APPVEYOR_PROJECT_SLUG/history?recordsNumber=50).builds | `
        Where-Object pullRequestId -eq $env:APPVEYOR_PULL_REQUEST_NUMBER)[0].buildNumber) { `
        throw "There are newer queued builds for this pull request, failing early." }

  # set up environment
  - "set PATH=%MINICONDA%;%MINICONDA%\\Scripts;%PATH%"
  - conda config --set always_yes yes --set show_channel_urls true --set changeps1 no
  - conda update -q conda
  - conda config --add channels conda-forge
  - conda info -a
  - conda env create -f environment.yml
  - activate matplotcheck-dev
  - pip install -e . --no-deps
  - pip install -r dev-requirements.txt

test_script:
  - conda list
  - conda info -a
  - pytest
